import 'package:api_example/network/model/task_model.dart';
import 'package:dio/dio.dart';
import 'package:pretty_dio_logger/pretty_dio_logger.dart';
import 'package:retrofit/retrofit.dart';
part 'api_service.g.dart';

@RestApi(baseUrl: "https://geoproxy.dev.iamplus.services/")
abstract class ApiService {
  factory ApiService(Dio dio, {String baseUrl}) = _ApiService;

  static ApiService create() {
    final dio = Dio();
    dio.interceptors.add(PrettyDioLogger());
    return ApiService(dio);
  }

  @GET("geocode?address=japan&language=en")
  Future<Autogenerated> getTasks();

  @GET("revgeocode?location=12.9536,77.49085")
  Future<Autogenerated> getData();
}